python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed1_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-258-2.csv --x 2 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed1_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-306-2.csv --x 2 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed1_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-258-306-2.csv --x 2 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed2_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-258-306-5.csv --x 5 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed2_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-258-5.csv --x 5 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed2_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-306-5.csv --x 5 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed3_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-306-10.csv --x 10 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed3_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-258-306-10.csv --x 10 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed3_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-258-10.csv --x 10 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed4_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-258-25.csv --x 25 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed4_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-258-306-25.csv --x 25 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed4_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-306-25.csv --x 25 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed5_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-306-50.csv --x 50 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed5_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-258-306-50.csv --x 50 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed5_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-258-50.csv --x 50 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed6_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-258-100.csv --x 100 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed6_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-258-306-100.csv --x 100 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed6_processed.csv --output_file data/owndata/attackdata/high-speed/high-ID-306-100.csv --x 100 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed7_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-306-2.csv --x 2 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed7_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-258-306-2.csv --x 2 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed7_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-258-2.csv --x 2 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed8_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-258-5.csv --x 5 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed8_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-258-306-5.csv --x 5 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed8_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-306-5.csv --x 5 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed9_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-306-10.csv --x 10 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed9_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-258-306-10.csv --x 10 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed9_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-258-10.csv --x 10 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed10_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-258-25.csv --x 25 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed10_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-258-306-25.csv --x 25 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed10_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-306-25.csv --x 25 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed11_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-306-50.csv --x 50 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed11_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-258-306-50.csv --x 50 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed11_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-258-50.csv --x 50 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed12_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-258-100.csv --x 100 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed12_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-258-306-100.csv --x 100 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed12_processed.csv --output_file data/owndata/attackdata/high-speed/high-data-306-100.csv --x 100 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed13_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-258-2.csv --x 2 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed13_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-258-306-2.csv --x 2 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed13_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-306-2.csv --x 2 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed14_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-306-5.csv --x 5 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed14_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-258-306-5.csv --x 5 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed14_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-258-5.csv --x 5 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed15_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-258-10.csv --x 10 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed15_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-258-306-10.csv --x 10 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed15_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-306-10.csv --x 10 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed16_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-306-25.csv --x 25 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed16_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-258-306-25.csv --x 25 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed16_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-258-25.csv --x 25 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed17_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-258-50.csv --x 50 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed17_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-258-306-50.csv --x 50 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed17_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-306-50.csv --x 50 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed18_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-306-100.csv --x 100 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed18_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-258-306-100.csv --x 100 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/high-speed/high-speed18_processed.csv --output_file data/owndata/attackdata/high-speed/high-both-258-100.csv --x 100 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed1_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-258-2.csv --x 2 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed1_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-306-2.csv --x 2 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed1_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-258-306-2.csv --x 2 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed2_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-258-306-5.csv --x 5 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed2_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-258-5.csv --x 5 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed2_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-306-5.csv --x 5 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed3_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-306-10.csv --x 10 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed3_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-258-306-10.csv --x 10 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed3_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-258-10.csv --x 10 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed4_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-258-25.csv --x 25 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed4_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-258-306-25.csv --x 25 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed4_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-306-25.csv --x 25 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed5_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-306-50.csv --x 50 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed5_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-258-306-50.csv --x 50 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed5_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-258-50.csv --x 50 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed6_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-258-100.csv --x 100 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed6_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-258-306-100.csv --x 100 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed6_processed.csv --output_file data/owndata/attackdata/low-speed/low-ID-306-100.csv --x 100 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed7_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-306-2.csv --x 2 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed7_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-258-306-2.csv --x 2 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed7_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-258-2.csv --x 2 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed8_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-258-5.csv --x 5 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed8_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-258-306-5.csv --x 5 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed8_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-306-5.csv --x 5 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed9_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-306-10.csv --x 10 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed9_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-258-306-10.csv --x 10 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed9_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-258-10.csv --x 10 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed10_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-258-25.csv --x 25 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed10_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-258-306-25.csv --x 25 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed10_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-306-25.csv --x 25 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed11_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-306-50.csv --x 50 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed11_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-258-306-50.csv --x 50 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed11_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-258-50.csv --x 50 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed12_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-258-100.csv --x 100 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed12_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-258-306-100.csv --x 100 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed12_processed.csv --output_file data/owndata/attackdata/low-speed/low-data-306-100.csv --x 100 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed13_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-258-2.csv --x 2 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed13_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-258-306-2.csv --x 2 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed13_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-306-2.csv --x 2 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed14_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-306-5.csv --x 5 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed14_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-258-306-5.csv --x 5 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed14_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-258-5.csv --x 5 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed15_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-258-10.csv --x 10 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed15_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-258-306-10.csv --x 10 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed15_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-306-10.csv --x 10 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed16_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-306-25.csv --x 25 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed16_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-258-306-25.csv --x 25 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed16_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-258-25.csv --x 25 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed17_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-258-50.csv --x 50 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed17_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-258-306-50.csv --x 50 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed17_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-306-50.csv --x 50 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed18_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-306-100.csv --x 100 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed18_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-258-306-100.csv --x 100 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/low-speed/low-speed18_processed.csv --output_file data/owndata/attackdata/low-speed/low-both-258-100.csv --x 100 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby1_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-258-2.csv --x 2 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby1_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-306-2.csv --x 2 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby1_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-258-306-2.csv --x 2 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby2_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-258-306-5.csv --x 5 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby2_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-258-5.csv --x 5 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby2_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-306-5.csv --x 5 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby3_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-306-10.csv --x 10 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby3_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-258-306-10.csv --x 10 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby3_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-258-10.csv --x 10 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby4_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-258-25.csv --x 25 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby4_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-258-306-25.csv --x 25 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby4_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-306-25.csv --x 25 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby5_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-306-50.csv --x 50 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby5_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-258-306-50.csv --x 50 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby5_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-258-50.csv --x 50 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby6_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-258-100.csv --x 100 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby6_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-258-306-100.csv --x 100 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby6_processed.csv --output_file data/owndata/attackdata/standby/standby-ID-306-100.csv --x 100 --modify_type CANID
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby7_processed.csv --output_file data/owndata/attackdata/standby/standby-data-306-2.csv --x 2 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby7_processed.csv --output_file data/owndata/attackdata/standby/standby-data-258-306-2.csv --x 2 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby7_processed.csv --output_file data/owndata/attackdata/standby/standby-data-258-2.csv --x 2 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby8_processed.csv --output_file data/owndata/attackdata/standby/standby-data-258-5.csv --x 5 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby8_processed.csv --output_file data/owndata/attackdata/standby/standby-data-258-306-5.csv --x 5 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby8_processed.csv --output_file data/owndata/attackdata/standby/standby-data-306-5.csv --x 5 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby9_processed.csv --output_file data/owndata/attackdata/standby/standby-data-306-10.csv --x 10 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby9_processed.csv --output_file data/owndata/attackdata/standby/standby-data-258-306-10.csv --x 10 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby9_processed.csv --output_file data/owndata/attackdata/standby/standby-data-258-10.csv --x 10 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby10_processed.csv --output_file data/owndata/attackdata/standby/standby-data-258-25.csv --x 25 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby10_processed.csv --output_file data/owndata/attackdata/standby/standby-data-258-306-25.csv --x 25 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby10_processed.csv --output_file data/owndata/attackdata/standby/standby-data-306-25.csv --x 25 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby11_processed.csv --output_file data/owndata/attackdata/standby/standby-data-306-50.csv --x 50 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby11_processed.csv --output_file data/owndata/attackdata/standby/standby-data-258-306-50.csv --x 50 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby11_processed.csv --output_file data/owndata/attackdata/standby/standby-data-258-50.csv --x 50 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby12_processed.csv --output_file data/owndata/attackdata/standby/standby-data-258-100.csv --x 100 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby12_processed.csv --output_file data/owndata/attackdata/standby/standby-data-258-306-100.csv --x 100 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby12_processed.csv --output_file data/owndata/attackdata/standby/standby-data-306-100.csv --x 100 --modify_type payload
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby13_processed.csv --output_file data/owndata/attackdata/standby/standby-both-258-2.csv --x 2 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby13_processed.csv --output_file data/owndata/attackdata/standby/standby-both-258-306-2.csv --x 2 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby13_processed.csv --output_file data/owndata/attackdata/standby/standby-both-306-2.csv --x 2 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby14_processed.csv --output_file data/owndata/attackdata/standby/standby-both-306-5.csv --x 5 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby14_processed.csv --output_file data/owndata/attackdata/standby/standby-both-258-306-5.csv --x 5 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby14_processed.csv --output_file data/owndata/attackdata/standby/standby-both-258-5.csv --x 5 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby15_processed.csv --output_file data/owndata/attackdata/standby/standby-both-258-10.csv --x 10 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby15_processed.csv --output_file data/owndata/attackdata/standby/standby-both-258-306-10.csv --x 10 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby15_processed.csv --output_file data/owndata/attackdata/standby/standby-both-306-10.csv --x 10 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby16_processed.csv --output_file data/owndata/attackdata/standby/standby-both-306-25.csv --x 25 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby16_processed.csv --output_file data/owndata/attackdata/standby/standby-both-258-306-25.csv --x 25 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby16_processed.csv --output_file data/owndata/attackdata/standby/standby-both-258-25.csv --x 25 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby17_processed.csv --output_file data/owndata/attackdata/standby/standby-both-258-50.csv --x 50 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby17_processed.csv --output_file data/owndata/attackdata/standby/standby-both-258-306-50.csv --x 50 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby17_processed.csv --output_file data/owndata/attackdata/standby/standby-both-306-50.csv --x 50 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby18_processed.csv --output_file data/owndata/attackdata/standby/standby-both-306-100.csv --x 100 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby18_processed.csv --output_file data/owndata/attackdata/standby/standby-both-258-306-100.csv --x 100 --modify_type Both
python scripts/modify_data.py --input_file data/owndata/processed/standby/standby18_processed.csv --output_file data/owndata/attackdata/standby/standby-both-258-100.csv --x 100 --modify_type Both